{"1":{"str":"php_pinpoint"},"2":{"str":"PHPApplication"},"3":{"i64":1537418088366},"4":{"str":"ABhwaHBfcGlucG9pbnSun4mq3ywi"},"7":{"i64":8309667280298585837},"8":{"i64":-1},"9":{"i64":1537418110731},"10":{"i32":1},"11":{"str":"/test_exception01.php"},"12":{"i16":1500},"13":{"str":"127.0.0.1:8989"},"14":{"str":"127.0.0.1"},"15":{"lst":["rec",1,{"1":{"i32":999},"2":{"rec":{"1":{"str":"/home/liumingyi/git/pinpoint-c-agent/simulate/testcase/php/trace/test_exception01"}}}}]},"16":{"i16":0},"17":{"i32":1},"18":{"lst":["rec",0]},"25":{"i32":-13},"26":{"rec":{"1":{"i32":-2},"2":{"str":"Fatal error: Uncaught exception 'Exception' with message 'Error Processing Request' in /home/liumingyi/git/pinpoint-c-agent/simulate/web/php/plugins/test_01_plugin.php:916\nStack trace:\n#0 /home/liumingyi/git/pinpoint-c-agent/simulate/web/php/test_exception01.php(23): TestException01Interceptor->onBefore(139, Array)\n#1 /home/liumingyi/git/pinpoint-c-agent/simulate/web/php/test_exception01.php(34): test_exception01->testFunc('sam')\n#2 {main}\n  thrown in /home/liumingyi/git/pinpoint-c-agent/simulate/web/php/plugins/test_01_plugin.php on line 916"}}}}